# Generated by Django 4.1.3 on 2023-04-10 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atendance',
            new_name='Attendance',
        ),
    ]
