# Generated by Django 4.2 on 2023-05-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='teacher',
            name='office',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
    ]
